language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - ./configure --prefix=$PWD/temp-build
  - make
  - make install
  - cd test
  - ./basic.sh
  - rm -rf tmp-home
  - ./purging.sh
  - cd ..
  - make uninstall

# safelist
branches:
  only:
  - master
  - travis_platforms

notifications:
  slack: removetowaste:u16fiNsaMeLmg7J4WXifW3Zm
